---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mybapi
spec:
  replicas: {{ .Values.mybapi.replicaCount }}
  selector:
    matchLabels:
      app: mybapi
  template:
    metadata:
      labels:
        app: mybapi
    spec:
      nodeSelector:
        {{- toYaml .Values.mybapi.nodeSelector | nindent 8 }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - mybapi
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: mybapi
          image: "{{ .Values.mybapi.image }}"
          imagePullPolicy: Never
          ports:
            - containerPort: {{ .Values.mybapi.port }}
          env:
            - name: BANK_POSTGRES_HOST
              value: "{{ .Values.mybapi.bankPostgresHost }}"
