---
apiVersion: v1
kind: Service
metadata:
  name: mybapi
spec:
  type: ClusterIP
  selector:
    app: mybapi
  ports:
    - protocol: TCP
      port: {{ .Values.mybapi.port }}
      targetPort: {{ .Values.mybapi.port }}
