services:
  postgres:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: bdb
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mybanknetwork
  mybapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development
      PORT: 8080
      BANK_POSTGRES_HOST: postgres:5432
    depends_on:
      - postgres
    networks:
      - mybanknetwork # Add to network

networks:
  mybanknetwork:
    driver: bridge

volumes:
  postgres_data:
